server:
  port: 8082

#配置rabbitMq 服务器
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: huangyan
    password: huangyan123


#datesource   mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/huangyan?&useUnicode=true&characterEncoding=UTF-8
    username: user
    password: 123456


#sql打印
logging:
  level:
    com:
      example:
        rabbitmqcustomer:
          mapper: DEBUG
